package main

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/nekoman-hq/neko-cli/plugin/release/pkg/release"
	"gopkg.in/yaml.v3"
)

const (
	goldenPathWorkflowStart = "<!-- golden-path-workflow:start -->"
	goldenPathWorkflowEnd   = "<!-- golden-path-workflow:end -->"
)

type documentedWorkflow struct {
	On struct {
		WorkflowDispatch struct {
			Inputs map[string]documentedWorkflowInput `yaml:"inputs"`
		} `yaml:"workflow_dispatch"`
	} `yaml:"on"`
	Permissions map[string]string `yaml:"permissions"`
	Jobs        map[string]struct {
		RunsOn string                   `yaml:"runs-on"`
		Env    map[string]string        `yaml:"env"`
		Steps  []documentedWorkflowStep `yaml:"steps"`
	} `yaml:"jobs"`
	Concurrency struct {
		Group            string `yaml:"group"`
		CancelInProgress bool   `yaml:"cancel-in-progress"`
	} `yaml:"concurrency"`
}

type documentedWorkflowInput struct {
	Description string `yaml:"description"`
	Type        string `yaml:"type"`
	Required    bool   `yaml:"required"`
}

type documentedWorkflowStep struct {
	Name  string            `yaml:"name"`
	ID    string            `yaml:"id"`
	Uses  string            `yaml:"uses"`
	Shell string            `yaml:"shell"`
	With  map[string]any    `yaml:"with"`
	Env   map[string]string `yaml:"env"`
	Run   string            `yaml:"run"`
}

func TestGitHubActionsGoldenPathWorkflowContract(t *testing.T) {
	document := readGoldenPathDocument(t)
	workflowYAML := extractGoldenPathWorkflow(t, document)
	marker := "# Generated by Neko Release workflow scaffolding.\n# Workflow contract version: 1\n# Create-only scaffold: customize consumer-owned steps after generation.\n"
	if !strings.HasPrefix(workflowYAML, marker) {
		t.Fatalf("generated workflow marker or contract version drifted")
	}

	var workflow documentedWorkflow
	if err := yaml.Unmarshal([]byte(workflowYAML), &workflow); err != nil {
		t.Fatalf("parse documented workflow YAML: %v", err)
	}

	expectedInputs := []string{"release_sha", "tag", "unit", "version"}
	actualInputs := make([]string, 0, len(workflow.On.WorkflowDispatch.Inputs))
	for name, input := range workflow.On.WorkflowDispatch.Inputs {
		actualInputs = append(actualInputs, name)
		if !input.Required {
			t.Errorf("workflow input %q must be required", name)
		}
		if input.Type != "string" {
			t.Errorf("workflow input %q type = %q, want string", name, input.Type)
		}
		if input.Description == "" {
			t.Errorf("workflow input %q must explain its authority", name)
		}
	}
	slices.Sort(actualInputs)
	if !slices.Equal(actualInputs, expectedInputs) {
		t.Fatalf("workflow inputs = %v, want exactly %v", actualInputs, expectedInputs)
	}

	if len(workflow.Permissions) != 1 || workflow.Permissions["contents"] != "read" {
		t.Errorf("workflow permissions = %v, want only contents: read", workflow.Permissions)
	}
	if workflow.Concurrency.Group != "release-${{ inputs.unit }}-${{ inputs.tag }}" {
		t.Errorf("concurrency group = %q, want unit and tag identity", workflow.Concurrency.Group)
	}
	if workflow.Concurrency.CancelInProgress {
		t.Error("release workflow must not cancel an in-progress release")
	}

	releaseJob, ok := workflow.Jobs["release"]
	if !ok {
		t.Fatal("documented workflow must define the release job")
	}
	if len(workflow.Jobs) != 1 {
		t.Fatalf("documented workflow jobs = %d, want only release", len(workflow.Jobs))
	}
	if releaseJob.RunsOn != "ubuntu-latest" {
		t.Errorf("release job runner = %q, want ubuntu-latest", releaseJob.RunsOn)
	}
	for name, value := range map[string]string{
		"RELEASE_UNIT":    "${{ inputs.unit }}",
		"RELEASE_VERSION": "${{ inputs.version }}",
		"RELEASE_TAG":     "${{ inputs.tag }}",
		"RELEASE_SHA":     "${{ inputs.release_sha }}",
	} {
		if releaseJob.Env[name] != value {
			t.Errorf("release job env %s = %q, want %q", name, releaseJob.Env[name], value)
		}
	}
	checkout := findDocumentedStep(t, releaseJob.Steps, "Checkout the exact release commit with tags")
	if checkout.Uses != "actions/checkout@v4" {
		t.Errorf("checkout action = %q, want actions/checkout@v4", checkout.Uses)
	}
	assertWorkflowValue(t, checkout.With, "ref", "${{ inputs.release_sha }}")
	assertWorkflowValue(t, checkout.With, "fetch-depth", "0")
	assertWorkflowValue(t, checkout.With, "fetch-tags", "true")
	assertWorkflowValue(t, checkout.With, "persist-credentials", "false")

	installCLI := findDocumentedStep(t, releaseJob.Steps, "Install pinned Neko CLI")
	for _, fragment := range []string{
		`: "${NEKO_VERSION:?Set repository variable NEKO_VERSION`,
		"https://raw.githubusercontent.com/nekoman-hq/neko-cli/main/install.sh",
		`bash "$RUNNER_TEMP/install-neko.sh"`,
		`echo "$NEKO_INSTALL_DIR" >> "$GITHUB_PATH"`,
	} {
		if !strings.Contains(installCLI.Run, fragment) {
			t.Errorf("Neko CLI installation is missing %q", fragment)
		}
	}
	if installCLI.Env["NEKO_VERSION"] != "${{ vars.NEKO_VERSION }}" {
		t.Errorf("Neko CLI version pin = %q", installCLI.Env["NEKO_VERSION"])
	}

	installPlugin := findDocumentedStep(t, releaseJob.Steps, "Install pinned Neko Release Plugin")
	if !strings.Contains(installPlugin.Run, `neko plugin install release --version "$NEKO_RELEASE_PLUGIN_VERSION"`) {
		t.Error("Release Plugin installation must use the explicit version pin")
	}
	if installPlugin.Env["NEKO_RELEASE_PLUGIN_VERSION"] != "${{ vars.NEKO_RELEASE_PLUGIN_VERSION }}" {
		t.Errorf("Release Plugin version pin = %q", installPlugin.Env["NEKO_RELEASE_PLUGIN_VERSION"])
	}

	validation := findDocumentedStep(t, releaseJob.Steps, "Validate Neko release context")
	if validation.Shell != "bash" {
		t.Errorf("context validation shell = %q, want bash", validation.Shell)
	}
	for _, fragment := range []string{
		"neko release ci-validate-context",
		"--unit \"$RELEASE_UNIT\"",
		"--version \"$RELEASE_VERSION\"",
		"--tag \"$RELEASE_TAG\"",
		"--release-sha \"$RELEASE_SHA\"",
		"--output github",
		"--github-output-file \"$GITHUB_OUTPUT\"",
	} {
		if !strings.Contains(validation.Run, fragment) {
			t.Errorf("context validation is missing %q", fragment)
		}
	}
	if strings.Contains(validation.Run, "${{") {
		t.Error("context validation must receive dispatch values through environment variables")
	}
	if validation.ID != "release-context" {
		t.Errorf("context validation step id = %q, want release-context", validation.ID)
	}
	for name, value := range map[string]string{
		"RELEASE_UNIT":    "${{ inputs.unit }}",
		"RELEASE_VERSION": "${{ inputs.version }}",
		"RELEASE_TAG":     "${{ inputs.tag }}",
		"RELEASE_SHA":     "${{ inputs.release_sha }}",
	} {
		if validation.Env[name] != value {
			t.Errorf("validation env %s = %q, want %q", name, validation.Env[name], value)
		}
	}
	for _, forbidden := range []string{"jq ", "fail()", "git rev-parse", "git show-ref"} {
		if strings.Contains(validation.Run, forbidden) {
			t.Errorf("context validation retained manual implementation %q", forbidden)
		}
	}

	consumer := findDocumentedStep(t, releaseJob.Steps, "Configure consumer build and publication")
	if consumer.Shell != "bash" {
		t.Errorf("consumer extension shell = %q, want bash", consumer.Shell)
	}
	for name, value := range map[string]string{
		"RELEASE_UNIT":    "${{ steps.release-context.outputs.unit }}",
		"RELEASE_VERSION": "${{ steps.release-context.outputs.version }}",
		"RELEASE_TAG":     "${{ steps.release-context.outputs.tag }}",
		"RELEASE_SHA":     "${{ steps.release-context.outputs.release_sha }}",
	} {
		if consumer.Env[name] != value {
			t.Errorf("consumer env %s = %q, want %q", name, consumer.Env[name], value)
		}
	}
	for _, fragment := range []string{
		"Replace this generated step with consumer-owned build and publication commands.",
		"exit 1",
	} {
		if !strings.Contains(consumer.Run, fragment) {
			t.Errorf("consumer extension point is missing %q", fragment)
		}
	}

	allCommands := validation.Run + "\n" + consumer.Run
	for _, forbidden := range []string{
		".release.neko.json",
		"neko release execute",
		"neko release patch",
		"neko release minor",
		"neko release major",
		"git commit",
		"git tag",
		"git push",
		"gh workflow run",
	} {
		if strings.Contains(allCommands, forbidden) {
			t.Errorf("documented workflow contains forbidden release-owner command %q", forbidden)
		}
	}
	if strings.Contains(workflowYAML, "secrets.") {
		t.Error("canonical build-system-neutral workflow must not assume consumer secrets")
	}
	for _, forbidden := range []string{"/Users/", "/home/", "C:\\\\"} {
		if strings.Contains(workflowYAML, forbidden) {
			t.Errorf("canonical workflow contains environment-specific absolute path %q", forbidden)
		}
	}
	for _, forbidden := range []string{
		"gh release",
		"actions/create-release",
		"softprops/action-gh-release",
		"gradle",
		"mvn ",
		"npm ",
		"pnpm ",
		"go build",
		"docker ",
		"make ",
	} {
		if strings.Contains(strings.ToLower(workflowYAML), forbidden) {
			t.Errorf("canonical workflow contains consumer publication or build assumption %q", forbidden)
		}
	}
}

func TestGitHubActionsGoldenPathUsesOnlyWorkflowDispatch(t *testing.T) {
	workflowYAML := extractGoldenPathWorkflow(t, readGoldenPathDocument(t))
	var document yaml.Node
	if err := yaml.Unmarshal([]byte(workflowYAML), &document); err != nil {
		t.Fatalf("parse documented workflow YAML: %v", err)
	}
	root := document.Content[0]
	for index := 0; index < len(root.Content); index += 2 {
		if root.Content[index].Value != "on" {
			continue
		}
		triggers := root.Content[index+1]
		if triggers.Kind != yaml.MappingNode || len(triggers.Content) != 2 || triggers.Content[0].Value != "workflow_dispatch" {
			t.Fatalf("workflow trigger must contain only workflow_dispatch: %#v", triggers.Content)
		}
		return
	}
	t.Fatal("documented workflow trigger is missing")
}

func TestGitHubActionsGoldenPathMatchesCanonicalWorkflowRenderer(t *testing.T) {
	documented := extractGoldenPathWorkflow(t, readGoldenPathDocument(t)) + "\n"
	generated, err := release.RenderCanonicalGitHubActionsReleaseWorkflow()
	if err != nil {
		t.Fatalf("render canonical GitHub Actions release workflow: %v", err)
	}
	if documented != string(generated) {
		t.Fatal("documented Golden Path workflow drifted from the canonical renderer")
	}
}

func TestGitHubActionsGoldenPathNavigation(t *testing.T) {
	root := repositoryRoot(t)
	paths := []string{
		"docs/release/overview.md",
		"docs/release/github-actions-delivery.md",
		"docs/release/cli-reference.md",
		"docs/release/examples.md",
		"docs/plugins/release.md",
	}
	for _, path := range paths {
		data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if err != nil {
			t.Fatalf("read navigation file %s: %v", path, err)
		}
		if !strings.Contains(string(data), "github-actions-golden-path.md") {
			t.Errorf("%s does not link to the canonical golden path", path)
		}
	}
}

func TestGitHubWorkflowScaffoldingDocumentationContract(t *testing.T) {
	root := repositoryRoot(t)
	documents := map[string][]string{
		"docs/release/github-actions-golden-path.md": {
			"neko release github-workflow-init",
			"create-only",
			"--dry-run",
			"different existing content",
			"Consumer-owned extension point",
			"no GitHub Release",
		},
		"docs/release/github-actions-delivery.md": {
			"neko release github-workflow-init",
			"multiple distinct",
			"byte-identical targets",
			"requires no token or network access",
		},
		"docs/release/cli-reference.md": {
			"github-workflow-init [--unit <unit-id>]",
			"WORKFLOW_TARGET_CONFLICT",
			"generated_content",
			"There is no provider, force, managed-update",
		},
		"docs/plugins/release.md": {
			"### `neko release github-workflow-init`",
			"atomic no-clobber",
			"Existing manually",
		},
		"docs/release/bootstrap-product-boundary.md": {
			"`github-workflow-init`",
			"managed workflow updates",
			"consumer-owned",
		},
		"plugin/release/docs/architecture/current-state.md": {
			"#### GitHub Actions workflow scaffolding",
			"Plan: `githubWorkflowGenerationPlanner`",
			"no writer",
		},
		"plugin/release/docs/architecture/architecture-decisions.md": {
			"Workflow scaffolding is focused",
			"create-only",
			"generic pipeline/state-machine",
		},
	}
	for path, fragments := range documents {
		content, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		for _, fragment := range fragments {
			if !strings.Contains(string(content), fragment) {
				t.Errorf("%s is missing workflow scaffolding contract %q", path, fragment)
			}
		}
	}
}

func readGoldenPathDocument(t *testing.T) string {
	t.Helper()
	path := filepath.Join(repositoryRoot(t), "docs", "release", "github-actions-golden-path.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden path document: %v", err)
	}
	return string(data)
}

func extractGoldenPathWorkflow(t *testing.T, document string) string {
	t.Helper()
	_, marked, found := strings.Cut(document, goldenPathWorkflowStart)
	if !found {
		t.Fatal("golden path workflow start marker is missing")
	}
	marked, _, found = strings.Cut(marked, goldenPathWorkflowEnd)
	if !found {
		t.Fatal("golden path workflow end marker is missing")
	}
	_, fenced, found := strings.Cut(marked, "```yaml\n")
	if !found {
		t.Fatal("golden path workflow YAML fence is missing")
	}
	workflowYAML, remainder, found := strings.Cut(fenced, "\n```")
	if !found || strings.TrimSpace(remainder) != "" {
		t.Fatal("golden path markers must contain exactly one YAML fence")
	}
	return workflowYAML
}

func findDocumentedStep(t *testing.T, steps []documentedWorkflowStep, name string) documentedWorkflowStep {
	t.Helper()
	for _, step := range steps {
		if step.Name == name {
			return step
		}
	}
	t.Fatalf("documented workflow step %q is missing", name)
	return documentedWorkflowStep{}
}

func assertWorkflowValue(t *testing.T, values map[string]any, name string, want string) {
	t.Helper()
	if got := fmt.Sprint(values[name]); got != want {
		t.Errorf("workflow value %s = %q, want %q", name, got, want)
	}
}
