package release

import (
	"context"
	"fmt"
	"strings"

	"github.com/nekoman-hq/neko-cli/pkg/log"
	releaseconfig "github.com/nekoman-hq/neko-cli/plugin/release/pkg/config"
)

// GitHubActionsReleaseRunner is the public facade for the active V2
// github-actions release use case.
type GitHubActionsReleaseRunner struct {
	coordinator    *GitReleaseCoordinator
	tokenResolver  GitHubActionsDispatchTokenResolver
	dispatchClient GitHubActionsWorkflowDispatchClient
	clock          ReleaseClock
}

type GitHubActionsReleaseRunnerOption func(*GitHubActionsReleaseRunner)

func NewGitHubActionsReleaseRunner(options ...GitHubActionsReleaseRunnerOption) *GitHubActionsReleaseRunner {
	client, _ := NewGitHubActionsDispatchClient()
	runner := &GitHubActionsReleaseRunner{
		coordinator:    NewGitReleaseCoordinator(),
		tokenResolver:  EnvironmentGitHubActionsDispatchTokenResolver{},
		dispatchClient: client,
		clock:          systemReleaseClock{},
	}
	for _, option := range options {
		if option != nil {
			option(runner)
		}
	}
	return runner
}

// WithGitHubActionsReleaseClock supplies all persisted timestamps generated by
// the active V2 release execution.
func WithGitHubActionsReleaseClock(clock ReleaseClock) GitHubActionsReleaseRunnerOption {
	return func(runner *GitHubActionsReleaseRunner) {
		if clock != nil {
			runner.clock = clock
		}
	}
}

func WithGitHubActionsReleaseTokenResolver(resolver GitHubActionsDispatchTokenResolver) GitHubActionsReleaseRunnerOption {
	return func(runner *GitHubActionsReleaseRunner) {
		if resolver != nil {
			runner.tokenResolver = resolver
		}
	}
}

func WithGitHubActionsReleaseDispatchClient(client GitHubActionsWorkflowDispatchClient) GitHubActionsReleaseRunnerOption {
	return func(runner *GitHubActionsReleaseRunner) {
		if client != nil {
			runner.dispatchClient = client
		}
	}
}

// GitHubActionsReleaseResult is safe user-facing release execution metadata.
type GitHubActionsReleaseResult struct {
	Unit                 string
	Version              string
	Tag                  string
	CommitSHA            string
	Workflow             string
	ExecutionJournalPath string
	DispatchJournalPath  string
	ExecutionState       ReleaseExecutionJournalState
	DispatchState        DispatchJournalState
	RecoveryGuidance     string
	DispatchRunURL       string
}

func (runner *GitHubActionsReleaseRunner) Run(ctx context.Context, execCtx *ReleaseExecutionContext) (*GitHubActionsReleaseResult, error) {
	if err := validateGitHubActionsReleaseRequest(execCtx); err != nil {
		return nil, err
	}
	logGitHubActionsReleaseRequest(execCtx)
	return runner.newUseCase(execCtx.RepositoryRoot).Run(ctx, execCtx)
}

func validateGitHubActionsReleaseRequest(execCtx *ReleaseExecutionContext) error {
	if execCtx == nil {
		return fmt.Errorf("release execution context is missing")
	}
	if execCtx.SourceFormat != releaseconfig.SourceFormatV2 {
		return fmt.Errorf("github-actions release runner supports V2 repositories only")
	}
	if execCtx.Delivery != string(releaseconfig.DeliveryGitHubActions) {
		return fmt.Errorf("V2 local release execution is not available yet")
	}
	if strings.TrimSpace(execCtx.Workflow) == "" {
		return fmt.Errorf("github-actions release requires a validated workflow")
	}
	return nil
}

func logGitHubActionsReleaseRequest(execCtx *ReleaseExecutionContext) {
	log.PluginPrint(log.Config, "Repository root: %s", execCtx.RepositoryRoot)
	log.PluginPrint(log.Config, "Release source format: %s", execCtx.SourceFormat)
	log.PluginPrint(log.Config, "Selected unit: %s", execCtx.Unit.ID)
	log.PluginPrint(log.Config, "Config path: %s", releaseconfig.V2ConfigPath(execCtx.RepositoryRoot))
	log.PluginPrint(log.Config, "State path: %s", releaseconfig.V2StatePath(execCtx.RepositoryRoot))
	log.PluginPrint(log.Exec, "Planning V2 release: current=%s next=%s tag=%s", execCtx.CurrentVersion, execCtx.NextVersion, execCtx.Tag)
	log.PluginPrint(log.Exec, "Executor=%s delivery=%s workflow=%s tagPrefix=%s", execCtx.Executor, execCtx.Delivery, execCtx.Workflow, execCtx.TagSpec.Prefix)
}
